# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='pub_date',
        ),
    ]
