# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_auto_20170824_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.Doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.Specialty', verbose_name='Специальность'),
        ),
    ]
