# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.Specialty', verbose_name='Специальность'),
        ),
    ]
