# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_auto_20170826_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'График'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
