# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_auto_20170827_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pub_date',
            field=models.DateTimeField(blank='True', max_length=15, verbose_name='Дата'),
        ),
    ]
